### ISSUE TITLE
ShiftGear address changed

### ISSUE THREAD

**Issue by wogns94** [FluffierKittens/SnowRunner-Disable-Auto-Reverse#1]
reference the https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod.git

exists shiftgrar address 0xd4d420 has an memory error.

I changed the address to 0xD4F040 and bulid the DLL file.

it is worked.

**Comment by FluffierKittens** [comment]
This mod is no longer being updated/maintained. All features (and more) are available in [SnowRunner-UI-Changes](https://github.com/FluffierKittens/SnowRunner-UI-Changes).
